/*
## [HttpYac](https://httpyac.github.io)

HttpYac lets you send and test REST, SOAP, GraphQL and gRPC requests.  

### Installation

* [VSCode Extension](https://open.vscode.dev/Anweber/httpyac)
    The VSCode Extension can be used to directly send requests from the editor.
*/
/*
### Authentication

The following requests require an auth token. This auth token is fetched first.  
You can change the values of 'Protocol' and 'baseurl' to target your roxtra installation.
Ensure 'username' and 'password' are correct to get a valid LoginToken.
*/
@protocol = http
@baseurl = localhost
@username = administrator
@password = admin

@host = {{protocol}}://{{baseurl}}/Roxtra/api/roxApi.svc/rest

# @name authentication
GET /Authenticate
Accept: application/json
Authorization: Basic {{username}} {{password}}

HTTP/1.1 200  - OK
cache-control: private
transfer-encoding: chunked
content-type: application/json; charset=utf-8
server: 
x-powered-by: 
x-roxtra-statuscode: 200
x-roxtra-version: 9.84.0
roxtraresponse: 200
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
report-to: { 'group': 'lbcsp', 'max-age': 10886400, 'endpoints': [{ 'url': 'https://csp.roxtra.com:7246/report' }] }
content-security-policy-report-only: report-uri https://csp.roxtra.com:7246/report; report-to lbcsp; default-src 'self' blob: data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; form-action 'self' https://login.microsoftonline.com; frame-ancestors 'self' https://login.microsoftonline.com; base-uri 'self'; object-src 'self'; connect-src 'self' data:; worker-src 'self' blob:;
content-security-policy: default-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; plugin-types 'none';
date: Wed, 20 Mar 2024 15:27:13 GMT
connection: close
###
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}

HTTP/1.1 200  - OK
cache-control: private
transfer-encoding: chunked
content-type: application/json; charset=utf-8
server: 
x-powered-by: 
x-roxtra-statuscode: 200
x-roxtra-version: 9.84.0
roxtraresponse: 200
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
report-to: { 'group': 'lbcsp', 'max-age': 10886400, 'endpoints': [{ 'url': 'https://csp.roxtra.com:7246/report' }] }
content-security-policy-report-only: report-uri https://csp.roxtra.com:7246/report; report-to lbcsp; default-src 'self' blob: data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; form-action 'self' https://login.microsoftonline.com; frame-ancestors 'self' https://login.microsoftonline.com; base-uri 'self'; object-src 'self'; connect-src 'self' data:; worker-src 'self' blob:;
content-security-policy: default-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; plugin-types 'none';
date: Wed, 20 Mar 2024 15:27:13 GMT
connection: close
/*
## Environment

The following request uses the [Authenticate file](./RoxtraAPI/Authenticate.http) before executing the actual request.  
The correct environment has to be chosen for the authentication to work. It holds all information to perform a successfull request to the endpoint.  
All environments are stored in the `/env` directory. Currently the `test.env` is the only environment for local testing.

Choosing the environment:

* VSCode:
    - The [httpYac](https://open.vscode.dev/Anweber/httpyac) module enables choosing a predefined environment on the sidebar.

* CLI:
    - The environment can be chosen with the `-e` option.
*/
###
# @import ./RoxtraAPI/Authenticate.http
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}

HTTP/1.1 200  - OK
cache-control: private
transfer-encoding: chunked
content-type: application/json; charset=utf-8
server: 
x-powered-by: 
x-roxtra-statuscode: 200
x-roxtra-version: 9.84.0
roxtraresponse: 200
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
report-to: { 'group': 'lbcsp', 'max-age': 10886400, 'endpoints': [{ 'url': 'https://csp.roxtra.com:7246/report' }] }
content-security-policy-report-only: report-uri https://csp.roxtra.com:7246/report; report-to lbcsp; default-src 'self' blob: data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; form-action 'self' https://login.microsoftonline.com; frame-ancestors 'self' https://login.microsoftonline.com; base-uri 'self'; object-src 'self'; connect-src 'self' data:; worker-src 'self' blob:;
content-security-policy: default-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; plugin-types 'none';
date: Wed, 20 Mar 2024 15:27:13 GMT
connection: close