/*
## [HttpYac](https://httpyac.github.io)

HttpYac lets you send and test REST, SOAP, GraphQL and gRPC requests.  

### Installation

* [httpYac](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) is a VSCode Extension which can be used to directly send requests from the editor.
* [httpBook](https://marketplace.visualstudio.com/items?itemName=anweber.httpbook) allows editing http files as a jupyter notebook. Markdown comments can be mixed with REST requests and responses will be saved. Responses can be cleared by deleting their cell.
*/
/*
### Authentication

The following requests require an auth token. This auth token is fetched first.  
You can change the values of 'Protocol' and 'baseurl' to target your roxtra installation.
Ensure 'username' and 'password' are correct to get a valid LoginToken.
*/
@protocol = http
@baseurl = localhost
@username = administrator
@password = admin

@host = {{protocol}}://{{baseurl}}/Roxtra/api/roxApi.svc/rest

# @name authentication
GET /Authenticate
Accept: application/json
Authorization: Basic {{username}} {{password}}
###
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}
/*
## Environment

The following request uses the [Authenticate file](./RoxtraAPI/Authenticate.http) before executing the actual request.  
The correct environment has to be chosen for the authentication to work. It holds all information to perform a successfull request to the endpoint.  
All environments are stored in the `/env` directory.

Choosing the environment:

* VSCode:
    - The [httpYac](https://marketplace.visualstudio.com/items?itemName=anweber.vscode-httpyac) module enables choosing a predefined environment on the sidebar.

* CLI:
    - The environment can be chosen with the `-e` option.
*/
###
# @import ./RoxtraAPI/Authenticate.http
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}