# @import ../RoxtraAPI/Authenticate.http
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}

?? status == 200
?? body includes Fields
?? body Id == 100
?? body Title == Dokumente

HTTP/1.1 200  - OK
cache-control: private
transfer-encoding: chunked
content-type: application/json; charset=utf-8
server: 
x-powered-by: 
x-roxtra-statuscode: 200
x-roxtra-version: 9.84.0
roxtraresponse: 200
referrer-policy: strict-origin-when-cross-origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
report-to: { 'group': 'lbcsp', 'max-age': 10886400, 'endpoints': [{ 'url': 'https://csp.roxtra.com:7246/report' }] }
content-security-policy-report-only: report-uri https://csp.roxtra.com:7246/report; report-to lbcsp; default-src 'self' blob: data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' blob: data:; style-src 'self' 'unsafe-inline'; form-action 'self' https://login.microsoftonline.com; frame-ancestors 'self' https://login.microsoftonline.com; base-uri 'self'; object-src 'self'; connect-src 'self' data:; worker-src 'self' blob:;
content-security-policy: default-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; plugin-types 'none';
date: Wed, 20 Mar 2024 12:16:18 GMT
connection: close