# @import ../RoxtraAPI/Authenticate.http
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}

?? status == 200
?? body includes Fields
?? body Id == 100
?? body Title == Documents