@Protocol = http
@baseurl = localhost

@host = {{Protocol}}://{{baseurl}}/Roxtra/api/roxApi.svc/rest

# @name authentication
GET /Authenticate
Accept: application/json
Authorization: Basic {{username}} {{password}}
###
# @ref authentication
GET /GetFolderDetails/100
Accept: application/json
authtoken: {{authentication.LoginToken}}