# @import ../RoxtraAPI/Authenticate.http
# @ref authentication
@folderId = {{$input Which folder should be requested? $value: 100}}
GET /GetFolderDetails/{{folderId}}
Accept: application/json
authtoken: {{authentication.LoginToken}}