/*
## Authentication Setting

roXtra Server Version. Additional info like **Date**, **Buildnumber** and the roXtra **Version**.
*/
# @import ./Authenticate.http
# @ref authentication
GET /AuthenticationSetting
Accept: application/json
authtoken: {{authentication.LoginToken}}