/*
## Authenticate

Authentication is done by providing username and password.
*/
@host = {{protocol}}://{{baseurl}}/Roxtra/api/roxApi.svc/{{restService}}

# @name authentication
GET /Authenticate
Accept: application/json
Authorization: Basic {{username}} {{password}}