# @import ./Authenticate.http
# @ref authentication
POST /CreateNewDocument
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

{
	"DestinationID": 100 ,
	"DestinationType" : 1,
	"DocTypeID": 100,
	"Fields": 
	[
		{
			"Id": "Title",
			"Value": "New api document"
		},
		{
			"Id": "Description",
			"Value": "new document created via roXtra api"
		}
	],
	"FileData": 
	{
		"Base64EncodedData": "SGVsbG8gV29ybGQh",
		"Filename": "Test.txt",
	}
}