/*
## Create New Document
*/
{{
	const fs = require('node:fs');
	const path = require('node:path');

	try {
		const data = fs.readFileSync(__dirname + '/' + filePath, 'utf8');
		exports.fileAsBase64 = Buffer.from(data.toString()).toString('base64');
		exports.fileName = path.parse(filePath).base;
	} catch (error) {
		console.error(error);
	}
}}


# @import ./Authenticate.http
# @ref authentication
POST /CreateNewDocument
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

{
	"DestinationID": 100 ,
	"DestinationType" : 1,
	"DocTypeID": 100,
	"Fields": 
	[
		{
			"Id": "Title",
			"Value": "New api document"
		},
		{
			"Id": "Description",
			"Value": "new document created via roXtra api"
		}
	],
	"FileData": 
	{
		"Base64EncodedData": "{{fileAsBase64}}",
		"Filename": "{{fileName}}",
	}
}