/*
## Download Export

Returns a zip-File as octed-stream of requested export.

Response header "checksum" contains default MD5 checksum hash of the file.

Response header "Content-Disposition" contains filename.
*/
@exportID = 1

# @import ./Authenticate.http
# @ref authentication
GET /Export/{{exportID}}/data
Accept: application/json
authtoken: {{authentication.LoginToken}}