/*
## Download Export

A simple request is made to get download an export by its ID.
*/
@exportID = 1

# @import ./Authenticate.http
# @ref authentication
GET /Export/{{exportID}}/data
Accept: application/json
authtoken: {{authentication.LoginToken}}