/*
## Get Changed Files

Returns a list of changed files since a given timestamp.
*/
@refDate = {{$datetime iso8601 14 d}}

# @import ./Authenticate.http
# @ref authentication
POST /GetChangedFiles
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

{
    "RefDate":"\/Date({{refDate}})\/",
    "DocTypeIDs":[],
    "ValidStatusIDs":[130]
}