/*
## Get Document Hash

Gets a document by its id and hash.
The requested file is directly shown in VSCode if httpBook is _not_ used.
*/
@documentID = 109
@documentHash = 0c36302b-0200-4367-b084-43ddcc1e36c5

# @import ./Authenticate.http
# @ref authentication
GET /GetDocumentHash/{{documentID}}/{{documentHash}}
Accept: application/json
authtoken: {{authentication.LoginToken}}