/*
## Get Document Hash

Returns a file stream of the requested roXtra file if the current file is different from the file on the server. The response is a file and the hash of the file in the header (HEADER: roxtra-file-hash:. This hash is used for later checks. Up to roXtra version 7.103 the MD5 hash of the file was used for this.  
The requested file is directly shown in VSCode if httpBook is _not_ used.
*/
@documentID = 109
@documentHash = 0c36302b-0200-4367-b084-43ddcc1e36c5

# @import ./Authenticate.http
# @ref authentication
GET /GetDocumentHash/{{documentID}}/{{documentHash}}
Accept: application/json
authtoken: {{authentication.LoginToken}}