/*
## Get Data

Gets a document by its id.  
The requested file is directly shown in VSCode if httpBook is _not_ used.
*/
@documentID = 109
@documentType = pdf

# @import ./Authenticate.http
# @ref authentication
GET /files/{{documentID}}/data/{{documentType}}
Accept: application/json
authtoken: {{authentication.LoginToken}}