/*
# Get Default Folder ID

Returns the default folder of the user. (e.g. Startfolder if set)
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetDefaultFolderID
Accept: application/json
authtoken: {{authentication.LoginToken}}