/*
## Get Document

Returns the original document by its id.  
The requested file is directly shown in VSCode if httpBook is _not_ used.
*/
@documentID = 109

# @import ./Authenticate.http
# @ref authentication
GET /GetDocument/{{documentID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}