/*
# Get Default Folder ID

A simple request is made to get the default folder ID.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetDefaultFolderID
Accept: application/json
authtoken: {{authentication.LoginToken}}