/*
## Get Escalation Details

Returns the details of the specified escalation.
*/
@escalationID = 0

# @import ./Authenticate.http
# @ref authentication
GET /GetEscalationDetails/{{escalationID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}