/*
## Get Export

Returns metadata of requested export.
*/
@exportID = 1

# @import ./Authenticate.http
# @ref authentication
GET /Export/{{exportID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}