/*
## Get Escalations

Returns all escalations of the current user.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetEscalations
Accept: application/json
authtoken: {{authentication.LoginToken}}