/*
## Get Favorites

Returns all favorites of the current user.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetFavorites
Accept: application/json
authtoken: {{authentication.LoginToken}}