/*
## Get File Simple

A simple request is made to get the file by a file ID.
*/
@fileID = 109

# @import ./Authenticate.http
# @ref authentication
GET /GetFileSimple/{{fileID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}