/*
## Get Folder Content

Returns the content of the specified folder.
*/
@folderID = 100

# @import ./Authenticate.http
# @ref authentication
GET /GetFolderContent/{{folderID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}