/*
## Get Folder Details

Folder details of a specific folder is requested.  
The authentication is done in advance.
*/
@folderId = 100

# @import ./Authenticate.http
# @ref authentication
GET /GetFolderDetails/{{folderId}}
Accept: application/json
authtoken: {{authentication.LoginToken}}