/*
## Get Folder Details

Returns all information of the specified folder.
*/
@folderID = 100

# @import ./Authenticate.http
# @ref authentication
GET /GetFolderDetails/{{folderID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}