/*
# Get Folder Content

A simple request is made to get the folder content by a folder ID.
*/
@folderID = 100

# @import ./Authenticate.http
# @ref authentication
GET /GetFolderContent/{{folderID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}