/*
# Get Personal Folder Content

Content of the personal folder.

Use the type parameter to specify what kind of content is returned:

*0 - Ordner und Dateien*

*1 - Dateien*

*2 - Ordner*
*/
@contentType = 0

# @import ./Authenticate.http
# @ref authentication
GET /GetPersonalFolderContent/{{contentType}}
Accept: application/json
authtoken: {{authentication.LoginToken}}