/*
# Get Root Folder ID

Returns the ID of the root folder.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetRootFolderID
Accept: application/json
authtoken: {{authentication.LoginToken}}