/*
# Get Roxtra Server Information

roXtra Server Information. Additional info like **BaseURL**, **DefaultLanguage** and the **EFormBaseURL**.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetRoxtraServerInformation
Accept: application/json
authtoken: {{authentication.LoginToken}}