/*
# Get RoXtra Version

roXtra Server Version. Additional info like **Date**, **Buildnumber** and the roXtra **Version**.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetRoxtraVersion
Accept: application/json
authtoken: {{authentication.LoginToken}}