/*
## Get Todo Details

Returns the details of the specified todo.
*/
@todoID = 0

# @import ./Authenticate.http
# @ref authentication
GET /GetTodoDetails/{{todoID}}
Accept: application/json
authtoken: {{authentication.LoginToken}}