/*
# Get User License

Returns the license of the current user.
*/
# @import ./Authenticate.http
# @ref authentication
GET /GetUserLicense
Accept: application/json
authtoken: {{authentication.LoginToken}}