/*
## Search Global

Searches for documents globally.

Used Enums:

* Mode - SearchMode  
and - 0  
or - 1  
exact - 2

* Type - SearchType [Flagable]  
fields = 1  
fulltext = 2

* DisplayType  
Depending on the folder views in roXtra
*/
@searchTerm = 'Pdf'
@docType = 0
@maxResults = 50
@searchMode = 1
@searchType = 1
@displayType = 1

# @import ./Authenticate.http
# @ref authentication
POST /SearchGlobal/{{searchTerm}}/{{docType}}/{{maxResults}}
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

{
	"IsGlobalSearch": true,
	"IsPersonalFolderSearch": false,
	"IsAdvancedSearch": false,
	"IsSpecialSearch": false,
	"ParentObjectOnly": false,
	"IsFolderSearch": false,
	"IsRecordSearch": false,
	"IsArchiveSearch": false,
	"Mode": {{searchMode}},
	"Type": {{searchType}},
	"DisplayType": {{displayType}}
}