/*
## Set File Fields

Updates Fields of the specified document.
*/
@fileID = 109

# @import ./Authenticate.http
# @ref authentication
POST /SetFileFields/{{fileID}}
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

[
	{
		"Id": "Description",
		"Value": "new description, set with api"
	}
]