/*
## Set To Do Status

Set the status of a todo. this function must be enabled via the configuration. (EnableMobileEdit)
*/
@todoID = 0
@todoDone = true

# @import ./Authenticate.http
# @ref authentication
GET /SetToDoStatus/{{todoID}}/{{todoDone}}
Accept: application/json
authtoken: {{authentication.LoginToken}}