/*
## Update Tree Selection (V2)

Endpoint to update tree views in multiple languages.
Post your complete view in order to update / create entries of the corresponding roXtra view. Entries which are not included in this request are deleted in roXtra.

Entries will be matched by
* ID
* or if ID = -1 by ExternalID
* or if preferExternalID is provided, ID is ignored
*/
@selectionID = EndProduct
@preferExternalID = 1

# @import ./Authenticate.http
# @ref authentication
POST /UpdateTreeSelectionV2/{{selectionID}}?{{preferExternalID}}
Accept: application/json
Content-Type: application/json
authtoken: {{authentication.LoginToken}}

[{
    "ID": -1,
    "ExternalID": "",
    "Translations": [
        { "Key": "de-DE", "Value": "Ebene 1" },
        { "Key": "en-US", "Value": "Level 1" }
    ],
    "Items": [
        {
            "ID": -1,
            "ExternalID": "",
            "Translations": [
                { "Key": "de-DE", "Value": "Ebene 1.1" },
                { "Key": "en-US", "Value": "Level 1.1" }
            ],
            "Items": [
                {
                    "ID": -1,
                    "ExternalID": "",
                    "Translations": [
                        { "Key": "de-DE", "Value": "Ebene 1.1.1" },
                        { "Key": "en-US", "Value": "Level 1.1.1" }
                    ],
                    "Items": [
                        {
                            "ID": -1,
                            "ExternalID": "",
                            "Translations": [
                                { "Key": "de-DE", "Value": "Ebene 1.1.1.1" },
                                { "Key": "en-US", "Value": "Level 1.1.1.1" }
                            ],
                            "Items": []
                        },
                        {
                            "ID": -1,
                            "ExternalID": "",
                            "Translations": [
                                { "Key": "de-DE", "Value": "Ebene 1.1.1.2" },
                                { "Key": "en-US", "Value": "Level 1.1.1.2" }
                            ],
                            "Items": []
                        }
                    ]
                }
            ]
        }
    ]
}]